# Generated by Django 3.2.12 on 2022-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('unlike', 'Unlike')], max_length=30),
        ),
    ]
