# Generated by Django 3.2.12 on 2022-05-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='recommend_movies',
            field=models.ManyToManyField(blank=True, related_name='recommended', to='movies.Movie'),
        ),
    ]
